### PR TITLE
bug fix with containing_bbox

### PR DESCRIPTION
**Pull request by crthomsen**

### CODE REVIEW

**Comment by jdumas** [comment]
Do you have a unit test for this?

**Comment by crthomsen** [comment]
No, but it didnt even compile before my changes.

**Comment by jdumas** [comment]
That's weird, haven't people been compiling this version of geogram for a while?

**Comment by crthomsen** [comment]
It doesnt compile when I call containing_boxes() as the following functions are not defined: 

containing_boxes_recursive()
containing_bbox_recursive()

The changes in the PR fixes the issues.

**Pull request merged**
